// filename: wit/guest.wit
package {{ namespace }}:{{ name }};

/// The "guest" world your mod resides in.
world guest {
    use wasvy:ecs/app@{{ wasvy_wit_version }}.{ {% for param in params %}{{ param }}, {% endfor %}};

    {% for system in systems %}
    {% if !system.desc.is_empty() %}// {{ system.desc }}
    {% endif %}export {{ system.name }}: func({% for arg in system.args %}{{ arg.name }}: {{ arg.param }}{% if !loop.last %}, {% endif %}{% endfor %});
    {% endfor %}

    /// This is important.
    /// This makes it so the WASM module must implement the guest required functions by the Bevy host.
    include wasvy:ecs/guest@{{ wasvy_wit_version }};
}
