package component:simple;

/// An example world for the component to target.
world example {
    use wasvy:ecs/app.{commands, query};

    /// An example system that runs on ModSetup
    export spawn-entities: func(commands: commands);

    /// Another example system that runs every Update
    export spin-cube: func(query: query);

    /// This is important.
    /// This makes it so the WASM module must implement the guest required functions by the Bevy host.
    include wasvy:ecs/guest;
}
