package component:guest-wit;

world example {
    use wasvy:ecs/app@0.0.7.{query, schedule, system, query-for};
    use wasvy-examples:bindings/components.{health};

    export heal-system: func(query: query);
    export pct-system: func(query: query);

    include wasvy:ecs/guest@0.0.7;
}
