// Generated by `wit-bindgen` 0.54.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasvy:ecs
//     component:go

package main

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	"runtime"
	"wit_component/export_wit_world"
	"wit_component/wasvy_ecs_app"
)

var staticPinner = runtime.Pinner{}
var exportReturnArea = uintptr(witRuntime.Allocate(&staticPinner, 0, 1))
var syncExportPinner = runtime.Pinner{}

//go:wasmexport spin-cube
func wasm_export_wit_world_spin_cube(arg0 int32) {

	export_wit_world.SpinCube(wasvy_ecs_app.QueryFromOwnHandle(int32(uintptr(arg0))))

}

//go:wasmexport my-system
func wasm_export_wit_world_my_system(arg0 int32, arg1 int32) {

	export_wit_world.MySystem(wasvy_ecs_app.CommandsFromOwnHandle(int32(uintptr(arg0))), wasvy_ecs_app.QueryFromOwnHandle(int32(uintptr(arg1))))

}

//go:wasmexport setup
func wasm_export_wit_world_setup(arg0 int32) {

	export_wit_world.Setup(wasvy_ecs_app.AppFromOwnHandle(int32(uintptr(arg0))))

}

// Unused, but present to make the compiler happy
func main() {}
