// Generated by `wit-bindgen` 0.54.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasvy:ecs
//     component:go

package wit_world

import (
	"wit_component/wasvy_ecs_app"
)

type Commands = wasvy_ecs_app.Commands
type Query = wasvy_ecs_app.Query
type App = wasvy_ecs_app.App
